package com.homework.hr.entities.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.homework.hr.entities.Locations;
import com.homework.hr.entities.Regions;

/**
 * Class _Countries was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Countries extends CayenneDataObject {

    public static final String COUNTRY_NAME_PROPERTY = "countryName";
    public static final String LOCATIONS_ARRAY_PROPERTY = "locationsArray";
    public static final String TO_REGIONS_PROPERTY = "toRegions";

    public static final String COUNTRY_ID_PK_COLUMN = "COUNTRY_ID";

    public void setCountryName(String countryName) {
        writeProperty("countryName", countryName);
    }
    public String getCountryName() {
        return (String)readProperty("countryName");
    }

    public void addToLocationsArray(Locations obj) {
        addToManyTarget("locationsArray", obj, true);
    }
    public void removeFromLocationsArray(Locations obj) {
        removeToManyTarget("locationsArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Locations> getLocationsArray() {
        return (List<Locations>)readProperty("locationsArray");
    }


    public void setToRegions(Regions toRegions) {
        setToOneTarget("toRegions", toRegions, true);
    }

    public Regions getToRegions() {
        return (Regions)readProperty("toRegions");
    }


}
