package com.homework.hr.entities.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.homework.hr.entities.Employees;
import com.homework.hr.entities.JobHistory;
import com.homework.hr.entities.Locations;

/**
 * Class _Departments was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Departments extends CayenneDataObject {

    public static final String DEPARTMENT_NAME_PROPERTY = "departmentName";
    public static final String EMPLOYEES_ARRAY_PROPERTY = "employeesArray";
    public static final String JOB_HISTORY_ARRAY_PROPERTY = "jobHistoryArray";
    public static final String TO_EMPLOYEES_PROPERTY = "toEmployees";
    public static final String TO_LOCATIONS_PROPERTY = "toLocations";

    public static final String DEPARTMENT_ID_PK_COLUMN = "DEPARTMENT_ID";

    public void setDepartmentName(String departmentName) {
        writeProperty("departmentName", departmentName);
    }
    public String getDepartmentName() {
        return (String)readProperty("departmentName");
    }

    public void addToEmployeesArray(Employees obj) {
        addToManyTarget("employeesArray", obj, true);
    }
    public void removeFromEmployeesArray(Employees obj) {
        removeToManyTarget("employeesArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Employees> getEmployeesArray() {
        return (List<Employees>)readProperty("employeesArray");
    }


    public void addToJobHistoryArray(JobHistory obj) {
        addToManyTarget("jobHistoryArray", obj, true);
    }
    public void removeFromJobHistoryArray(JobHistory obj) {
        removeToManyTarget("jobHistoryArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<JobHistory> getJobHistoryArray() {
        return (List<JobHistory>)readProperty("jobHistoryArray");
    }


    public void setToEmployees(Employees toEmployees) {
        setToOneTarget("toEmployees", toEmployees, true);
    }

    public Employees getToEmployees() {
        return (Employees)readProperty("toEmployees");
    }


    public void setToLocations(Locations toLocations) {
        setToOneTarget("toLocations", toLocations, true);
    }

    public Locations getToLocations() {
        return (Locations)readProperty("toLocations");
    }


}
