package com.homework.hr.entities.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _EmpDetailsView was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EmpDetailsView extends CayenneDataObject {

    public static final String CITY_PROPERTY = "city";
    public static final String COMMISSION_PCT_PROPERTY = "commissionPct";
    public static final String COUNTRY_ID_PROPERTY = "countryId";
    public static final String COUNTRY_NAME_PROPERTY = "countryName";
    public static final String DEPARTMENT_ID_PROPERTY = "departmentId";
    public static final String DEPARTMENT_NAME_PROPERTY = "departmentName";
    public static final String EMPLOYEE_ID_PROPERTY = "employeeId";
    public static final String FIRST_NAME_PROPERTY = "firstName";
    public static final String JOB_ID_PROPERTY = "jobId";
    public static final String JOB_TITLE_PROPERTY = "jobTitle";
    public static final String LAST_NAME_PROPERTY = "lastName";
    public static final String LOCATION_ID_PROPERTY = "locationId";
    public static final String MANAGER_ID_PROPERTY = "managerId";
    public static final String REGION_NAME_PROPERTY = "regionName";
    public static final String SALARY_PROPERTY = "salary";
    public static final String STATE_PROVINCE_PROPERTY = "stateProvince";

    public static final String EMPLOYEE_ID_PK_COLUMN = "EMPLOYEE_ID";

    public void setCity(String city) {
        writeProperty("city", city);
    }
    public String getCity() {
        return (String)readProperty("city");
    }

    public void setCommissionPct(BigDecimal commissionPct) {
        writeProperty("commissionPct", commissionPct);
    }
    public BigDecimal getCommissionPct() {
        return (BigDecimal)readProperty("commissionPct");
    }

    public void setCountryId(String countryId) {
        writeProperty("countryId", countryId);
    }
    public String getCountryId() {
        return (String)readProperty("countryId");
    }

    public void setCountryName(String countryName) {
        writeProperty("countryName", countryName);
    }
    public String getCountryName() {
        return (String)readProperty("countryName");
    }

    public void setDepartmentId(Integer departmentId) {
        writeProperty("departmentId", departmentId);
    }
    public Integer getDepartmentId() {
        return (Integer)readProperty("departmentId");
    }

    public void setDepartmentName(String departmentName) {
        writeProperty("departmentName", departmentName);
    }
    public String getDepartmentName() {
        return (String)readProperty("departmentName");
    }

    public void setEmployeeId(Integer employeeId) {
        writeProperty("employeeId", employeeId);
    }
    public Integer getEmployeeId() {
        return (Integer)readProperty("employeeId");
    }

    public void setFirstName(String firstName) {
        writeProperty("firstName", firstName);
    }
    public String getFirstName() {
        return (String)readProperty("firstName");
    }

    public void setJobId(String jobId) {
        writeProperty("jobId", jobId);
    }
    public String getJobId() {
        return (String)readProperty("jobId");
    }

    public void setJobTitle(String jobTitle) {
        writeProperty("jobTitle", jobTitle);
    }
    public String getJobTitle() {
        return (String)readProperty("jobTitle");
    }

    public void setLastName(String lastName) {
        writeProperty("lastName", lastName);
    }
    public String getLastName() {
        return (String)readProperty("lastName");
    }

    public void setLocationId(Integer locationId) {
        writeProperty("locationId", locationId);
    }
    public Integer getLocationId() {
        return (Integer)readProperty("locationId");
    }

    public void setManagerId(Integer managerId) {
        writeProperty("managerId", managerId);
    }
    public Integer getManagerId() {
        return (Integer)readProperty("managerId");
    }

    public void setRegionName(String regionName) {
        writeProperty("regionName", regionName);
    }
    public String getRegionName() {
        return (String)readProperty("regionName");
    }

    public void setSalary(BigDecimal salary) {
        writeProperty("salary", salary);
    }
    public BigDecimal getSalary() {
        return (BigDecimal)readProperty("salary");
    }

    public void setStateProvince(String stateProvince) {
        writeProperty("stateProvince", stateProvince);
    }
    public String getStateProvince() {
        return (String)readProperty("stateProvince");
    }

}
