package com.homework.hr.entities.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.homework.hr.entities.Departments;
import com.homework.hr.entities.Employees;
import com.homework.hr.entities.JobHistory;
import com.homework.hr.entities.Jobs;

/**
 * Class _Employees was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Employees extends CayenneDataObject {

    public static final String COMMISSION_PCT_PROPERTY = "commissionPct";
    public static final String EMAIL_PROPERTY = "email";
    public static final String FIRST_NAME_PROPERTY = "firstName";
    public static final String HIRE_DATE_PROPERTY = "hireDate";
    public static final String LAST_NAME_PROPERTY = "lastName";
    public static final String PHONE_NUMBER_PROPERTY = "phoneNumber";
    public static final String SALARY_PROPERTY = "salary";
    public static final String DEPARTMENTS_ARRAY_PROPERTY = "departmentsArray";
    public static final String EMPLOYEES_ARRAY_PROPERTY = "employeesArray";
    public static final String JOB_HISTORY_ARRAY_PROPERTY = "jobHistoryArray";
    public static final String TO_DEPARTMENTS_PROPERTY = "toDepartments";
    public static final String TO_EMPLOYEES_PROPERTY = "toEmployees";
    public static final String TO_JOBS_PROPERTY = "toJobs";

    public static final String EMPLOYEE_ID_PK_COLUMN = "EMPLOYEE_ID";

    public void setCommissionPct(BigDecimal commissionPct) {
        writeProperty("commissionPct", commissionPct);
    }
    public BigDecimal getCommissionPct() {
        return (BigDecimal)readProperty("commissionPct");
    }

    public void setEmail(String email) {
        writeProperty("email", email);
    }
    public String getEmail() {
        return (String)readProperty("email");
    }

    public void setFirstName(String firstName) {
        writeProperty("firstName", firstName);
    }
    public String getFirstName() {
        return (String)readProperty("firstName");
    }

    public void setHireDate(Date hireDate) {
        writeProperty("hireDate", hireDate);
    }
    public Date getHireDate() {
        return (Date)readProperty("hireDate");
    }

    public void setLastName(String lastName) {
        writeProperty("lastName", lastName);
    }
    public String getLastName() {
        return (String)readProperty("lastName");
    }

    public void setPhoneNumber(String phoneNumber) {
        writeProperty("phoneNumber", phoneNumber);
    }
    public String getPhoneNumber() {
        return (String)readProperty("phoneNumber");
    }

    public void setSalary(BigDecimal salary) {
        writeProperty("salary", salary);
    }
    public BigDecimal getSalary() {
        return (BigDecimal)readProperty("salary");
    }

    public void addToDepartmentsArray(Departments obj) {
        addToManyTarget("departmentsArray", obj, true);
    }
    public void removeFromDepartmentsArray(Departments obj) {
        removeToManyTarget("departmentsArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Departments> getDepartmentsArray() {
        return (List<Departments>)readProperty("departmentsArray");
    }


    public void addToEmployeesArray(Employees obj) {
        addToManyTarget("employeesArray", obj, true);
    }
    public void removeFromEmployeesArray(Employees obj) {
        removeToManyTarget("employeesArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Employees> getEmployeesArray() {
        return (List<Employees>)readProperty("employeesArray");
    }


    public void addToJobHistoryArray(JobHistory obj) {
        addToManyTarget("jobHistoryArray", obj, true);
    }
    public void removeFromJobHistoryArray(JobHistory obj) {
        removeToManyTarget("jobHistoryArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<JobHistory> getJobHistoryArray() {
        return (List<JobHistory>)readProperty("jobHistoryArray");
    }


    public void setToDepartments(Departments toDepartments) {
        setToOneTarget("toDepartments", toDepartments, true);
    }

    public Departments getToDepartments() {
        return (Departments)readProperty("toDepartments");
    }


    public void setToEmployees(Employees toEmployees) {
        setToOneTarget("toEmployees", toEmployees, true);
    }

    public Employees getToEmployees() {
        return (Employees)readProperty("toEmployees");
    }


    public void setToJobs(Jobs toJobs) {
        setToOneTarget("toJobs", toJobs, true);
    }

    public Jobs getToJobs() {
        return (Jobs)readProperty("toJobs");
    }


}
