package com.homework.hr.entities.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import com.homework.hr.entities.Departments;
import com.homework.hr.entities.Employees;
import com.homework.hr.entities.Jobs;

/**
 * Class _JobHistory was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _JobHistory extends CayenneDataObject {

    public static final String END_DATE_PROPERTY = "endDate";
    public static final String TO_DEPARTMENTS_PROPERTY = "toDepartments";
    public static final String TO_EMPLOYEES_PROPERTY = "toEmployees";
    public static final String TO_JOBS_PROPERTY = "toJobs";

    public static final String EMPLOYEE_ID_PK_COLUMN = "EMPLOYEE_ID";
    public static final String START_DATE_PK_COLUMN = "START_DATE";

    public void setEndDate(Date endDate) {
        writeProperty("endDate", endDate);
    }
    public Date getEndDate() {
        return (Date)readProperty("endDate");
    }

    public void setToDepartments(Departments toDepartments) {
        setToOneTarget("toDepartments", toDepartments, true);
    }

    public Departments getToDepartments() {
        return (Departments)readProperty("toDepartments");
    }


    public void setToEmployees(Employees toEmployees) {
        setToOneTarget("toEmployees", toEmployees, true);
    }

    public Employees getToEmployees() {
        return (Employees)readProperty("toEmployees");
    }


    public void setToJobs(Jobs toJobs) {
        setToOneTarget("toJobs", toJobs, true);
    }

    public Jobs getToJobs() {
        return (Jobs)readProperty("toJobs");
    }


}
