package com.homework.hr.entities.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.homework.hr.entities.Employees;
import com.homework.hr.entities.JobHistory;

/**
 * Class _Jobs was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Jobs extends CayenneDataObject {

    public static final String JOB_TITLE_PROPERTY = "jobTitle";
    public static final String MAX_SALARY_PROPERTY = "maxSalary";
    public static final String MIN_SALARY_PROPERTY = "minSalary";
    public static final String EMPLOYEES_ARRAY_PROPERTY = "employeesArray";
    public static final String JOB_HISTORY_ARRAY_PROPERTY = "jobHistoryArray";

    public static final String JOB_ID_PK_COLUMN = "JOB_ID";

    public void setJobTitle(String jobTitle) {
        writeProperty("jobTitle", jobTitle);
    }
    public String getJobTitle() {
        return (String)readProperty("jobTitle");
    }

    public void setMaxSalary(Integer maxSalary) {
        writeProperty("maxSalary", maxSalary);
    }
    public Integer getMaxSalary() {
        return (Integer)readProperty("maxSalary");
    }

    public void setMinSalary(Integer minSalary) {
        writeProperty("minSalary", minSalary);
    }
    public Integer getMinSalary() {
        return (Integer)readProperty("minSalary");
    }

    public void addToEmployeesArray(Employees obj) {
        addToManyTarget("employeesArray", obj, true);
    }
    public void removeFromEmployeesArray(Employees obj) {
        removeToManyTarget("employeesArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Employees> getEmployeesArray() {
        return (List<Employees>)readProperty("employeesArray");
    }


    public void addToJobHistoryArray(JobHistory obj) {
        addToManyTarget("jobHistoryArray", obj, true);
    }
    public void removeFromJobHistoryArray(JobHistory obj) {
        removeToManyTarget("jobHistoryArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<JobHistory> getJobHistoryArray() {
        return (List<JobHistory>)readProperty("jobHistoryArray");
    }


}
