package com.homework.hr.entities.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.homework.hr.entities.Countries;
import com.homework.hr.entities.Departments;

/**
 * Class _Locations was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Locations extends CayenneDataObject {

    public static final String CITY_PROPERTY = "city";
    public static final String POSTAL_CODE_PROPERTY = "postalCode";
    public static final String STATE_PROVINCE_PROPERTY = "stateProvince";
    public static final String STREET_ADDRESS_PROPERTY = "streetAddress";
    public static final String DEPARTMENTS_ARRAY_PROPERTY = "departmentsArray";
    public static final String TO_COUNTRIES_PROPERTY = "toCountries";

    public static final String LOCATION_ID_PK_COLUMN = "LOCATION_ID";

    public void setCity(String city) {
        writeProperty("city", city);
    }
    public String getCity() {
        return (String)readProperty("city");
    }

    public void setPostalCode(String postalCode) {
        writeProperty("postalCode", postalCode);
    }
    public String getPostalCode() {
        return (String)readProperty("postalCode");
    }

    public void setStateProvince(String stateProvince) {
        writeProperty("stateProvince", stateProvince);
    }
    public String getStateProvince() {
        return (String)readProperty("stateProvince");
    }

    public void setStreetAddress(String streetAddress) {
        writeProperty("streetAddress", streetAddress);
    }
    public String getStreetAddress() {
        return (String)readProperty("streetAddress");
    }

    public void addToDepartmentsArray(Departments obj) {
        addToManyTarget("departmentsArray", obj, true);
    }
    public void removeFromDepartmentsArray(Departments obj) {
        removeToManyTarget("departmentsArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Departments> getDepartmentsArray() {
        return (List<Departments>)readProperty("departmentsArray");
    }


    public void setToCountries(Countries toCountries) {
        setToOneTarget("toCountries", toCountries, true);
    }

    public Countries getToCountries() {
        return (Countries)readProperty("toCountries");
    }


}
