package com.homework.hr.entities.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.homework.hr.entities.Countries;

/**
 * Class _Regions was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Regions extends CayenneDataObject {

    public static final String REGION_NAME_PROPERTY = "regionName";
    public static final String COUNTRIES_ARRAY_PROPERTY = "countriesArray";

    public static final String REGION_ID_PK_COLUMN = "REGION_ID";

    public void setRegionName(String regionName) {
        writeProperty("regionName", regionName);
    }
    public String getRegionName() {
        return (String)readProperty("regionName");
    }

    public void addToCountriesArray(Countries obj) {
        addToManyTarget("countriesArray", obj, true);
    }
    public void removeFromCountriesArray(Countries obj) {
        removeToManyTarget("countriesArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Countries> getCountriesArray() {
        return (List<Countries>)readProperty("countriesArray");
    }


}
